### ISSUE TITLE
ImportError: cannot import name 'addstr'

### ISSUE THREAD

**Issue by zyugyzarc** [shohamp/culour#4]
### i have the following issue:
```
$ pip3 install culour
$ python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import culour
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zyugyzarc/.local/lib/python3.8/site-packages/culour/__init__.py", line 1, in <module>
    from culour import addstr
ImportError: cannot import name 'addstr' from partially initialized module 'culour' (most likely due to a circular import) (/home/zyugyzarc/.local/lib/python3.8/site-packages/culour/__init__.py)
```

config: amd/ubuntu_64, Konsole as a terminal.

**Comment by Taguar258** [comment]
@1v seems to have fixed it but it probably hasn't been pushed to pypi yet.

**Comment by Taguar258** [comment]
I am reopening this issue as it hasn't been resolved as of now.

**Comment by spellr** [comment]
pushed 👍
Thanks for flagging!
